#!/usr/bin/env python
# -*- coding: utf-8
#
# munin-murmur.py - "murmur stats (User/Bans/Uptime/Channels)" script for munin.
# Copyright (c) 2012, Natenom / natenom@natenom.name
# modified by Benjamin Neff <benjamin@coding4coffee.ch>
#         and Lennart Buhl <git@hackmate.de>

#Hardcoded Bot names
botnames = ["fluffy", "NetiMusicBot_v2"]
botsuffix = "-bot"

#Define threshold for idling (seconds)
idletime = 300 # 5 minutes

#Path to Murmur.ice
iceslice='/usr/share/slice/Murmur.ice'

#Includepath for Ice, this is default for Debian
iceincludepath="/usr/share/Ice/slice"

#Murmur-Port (not needed to work, only for display purposes)
serverport=64738

#Port where ice listen
iceport=6502

#Ice Password to get read access.
#If there is no such var in your murmur.ini, this can have any value.
#You can use the values of icesecret, icesecretread or icesecretwrite in your murmur.ini
icesecret="secureme"

#MessageSizeMax; increase this value, if you get a MemoryLimitException.
# Also check this value in murmur.ini of your Mumble-Server.
# This value is being interpreted in kibiBytes.
messagesizemax="65535"

import Ice, sys
Ice.loadSlice("--all -I%s %s" % (iceincludepath, iceslice))

props = Ice.createProperties([])
props.setProperty("Ice.MessageSizeMax", str(messagesizemax))
props.setProperty("Ice.ImplicitContext", "Shared")
id = Ice.InitializationData()
id.properties = props

ice = Ice.initialize(id)
ice.getImplicitContext().put("secret", icesecret)

import Murmur

if (sys.argv[1:]):
  if (sys.argv[1] == "config"):
    print 'graph_title Murmur (Port %s)' % (serverport)
    print 'graph_vlabel Count'
    print 'graph_category mumble'
    print 'users.label Users (All)'
    print 'usersnotauth.label Users (Not authenticated)'
    print 'usersmuted.label Users (Muted)'
    print 'usersbots.label Users (Bots)'
    print 'usersactive.label Users (Active)'
    print 'chancount.label Channelcount/10'
    print 'bancount.label Bans on server'
    sys.exit(0)


# Available Murmur ICE functionality:
#   https://github.com/mumble-voip/mumble/blob/master/src/murmur/Murmur.ice
meta = Murmur.MetaPrx.checkedCast(ice.stringToProxy("Meta:tcp -h 127.0.0.1 -p %s" % (iceport)))
try:
    server=meta.getServer(1)
except Murmur.InvalidSecretException: 
    print 'Given icesecreatread password is wrong.'
    ice.shutdown()
    sys.exit(1)

ismute = lambda usr: usr.mute or usr.selfMute or usr.suppress
isbot = lambda usr: usr.name in botnames or usr.name.endswith(botsuffix)

#count users
usersnotauth=0
usersmuted=0
usersbots=0
usersactive=0
users=server.getUsers()
for key in users.keys():
  user = users[key]
  if (user.userid == -1):
    usersnotauth+=1
  if ismute(user):
    usersmuted+=1
  if isbot(user):
    usersbots+=1
  if not (ismute(user) or isbot(user) or user.idlesecs > idletime):
    usersactive+=1

print "users.value %i" % (len(users))
print "usersnotauth.value %i" % (usersnotauth)
print "usersmuted.value %i" % (usersmuted)
print "usersbots.value %i" % (usersbots)
print "usersactive.value %i" % (usersactive)
print "chancount.value %.1f" % (len(server.getChannels())/10.0)
print "bancount.value %i" % (len(server.getBans()))
  
ice.shutdown()
